[book]
authors = ["Ruben Moor"]
language = "de"
multilingual = false
src = "src"
title = "Etatismus"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/rubenmoor/etatismus"

[output.html.fold]
enable = true
level = 2
